# Copyright (C) 2023 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/micromax/A109/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/micromax/A109/proprietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
    vendor/micromax/A109/proprietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
    vendor/micromax/A109/proprietary/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
    vendor/micromax/A109/proprietary/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
    vendor/micromax/A109/proprietary/etc/firmware/WIFI_RAM_CODE_MT6630:system/etc/firmware/WIFI_RAM_CODE_MT6630 \
    vendor/micromax/A109/proprietary/etc/firmware/WIFI_RAM_CODE_SOC:system/etc/firmware/WIFI_RAM_CODE_SOC \
    vendor/micromax/A109/proprietary/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
    vendor/micromax/A109/proprietary/etc/firmware/catcher_filter_1_3g_n.bin:system/etc/firmware/catcher_filter_1_3g_n.bin \
    vendor/micromax/A109/proprietary/etc/firmware/modem_1_3g_n.img:system/etc/firmware/modem_1_3g_n.img \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_rom.bin:system/etc/firmware/mt6628/mt6628_fm_rom.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v1_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v1_patch.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v2_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v2_patch.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v3_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v3_patch.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v4_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v4_patch.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628/mt6628_fm_v5_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v5_patch.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628_ant_m1.cfg:system/etc/firmware/mt6628_ant_m1.cfg \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628_patch_e1_hdr.bin:system/etc/firmware/mt6628_patch_e1_hdr.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628_patch_e2_0_hdr.bin:system/etc/firmware/mt6628_patch_e2_0_hdr.bin \
    vendor/micromax/A109/proprietary/etc/firmware/mt6628_patch_e2_1_hdr.bin:system/etc/firmware/mt6628_patch_e2_1_hdr.bin \
    vendor/micromax/A109/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/micromax/A109/proprietary/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/micromax/A109/proprietary/vendor/bin/rc.fac:system/vendor/bin/rc.fac \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/Banner/72:system/vendor/data/MAd/mdcall/mAdCall/Banner/72 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/Banner/73:system/vendor/data/MAd/mdcall/mAdCall/Banner/73 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/Banner/74:system/vendor/data/MAd/mdcall/mAdCall/Banner/74 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/Banner/75:system/vendor/data/MAd/mdcall/mAdCall/Banner/75 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/Banner/76:system/vendor/data/MAd/mdcall/mAdCall/Banner/76 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreAds/72:system/vendor/data/MAd/mdcall/mAdCall/PreAds/72 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreAds/73:system/vendor/data/MAd/mdcall/mAdCall/PreAds/73 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreAds/74:system/vendor/data/MAd/mdcall/mAdCall/PreAds/74 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreAds/75:system/vendor/data/MAd/mdcall/mAdCall/PreAds/75 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreAds/76:system/vendor/data/MAd/mdcall/mAdCall/PreAds/76 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreImages/19:system/vendor/data/MAd/mdcall/mAdCall/PreImages/19 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreImages/20:system/vendor/data/MAd/mdcall/mAdCall/PreImages/20 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreImages/21:system/vendor/data/MAd/mdcall/mAdCall/PreImages/21 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/PreImages/22:system/vendor/data/MAd/mdcall/mAdCall/PreImages/22 \
    vendor/micromax/A109/proprietary/vendor/data/MAd/mdcall/mAdCall/inbuild_XML/inbuild.xml:system/vendor/data/MAd/mdcall/mAdCall/inbuild_XML/inbuild.xml \
    vendor/micromax/A109/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/micromax/A109/proprietary/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
    vendor/micromax/A109/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
    vendor/micromax/A109/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
    vendor/micromax/A109/proprietary/vendor/lib/hw/audio.a2dp.blueangel.so:system/vendor/lib/hw/audio.a2dp.blueangel.so \
    vendor/micromax/A109/proprietary/vendor/lib/hw/bluetooth.blueangel.so:system/vendor/lib/hw/bluetooth.blueangel.so \
    vendor/micromax/A109/proprietary/vendor/lib/hw/gralloc.mt6589.so:system/vendor/lib/hw/gralloc.mt6589.so \
    vendor/micromax/A109/proprietary/vendor/lib/libBLPP.so:system/vendor/lib/libBLPP.so \
    vendor/micromax/A109/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/micromax/A109/proprietary/vendor/lib/libMusicHunterClient.so:system/vendor/lib/libMusicHunterClient.so \
    vendor/micromax/A109/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/micromax/A109/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/micromax/A109/proprietary/vendor/lib/libcleaninject.so:system/vendor/lib/libcleaninject.so \
    vendor/micromax/A109/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/micromax/A109/proprietary/vendor/lib/libkcmutil.so:system/vendor/lib/libkcmutil.so \
    vendor/micromax/A109/proprietary/vendor/lib/libmessagebox_ext.so:system/vendor/lib/libmessagebox_ext.so \
    vendor/micromax/A109/proprietary/vendor/lib/libom.so:system/vendor/lib/libom.so \
    vendor/micromax/A109/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/micromax/A109/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/micromax/A109/proprietary/vendor/lib/libs3efacebook_ext.so:system/vendor/lib/libs3efacebook_ext.so \
    vendor/micromax/A109/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/micromax/A109/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/micromax/A109/proprietary/vendor/lib/libswiftkeysdk-java-internal.so:system/vendor/lib/libswiftkeysdk-java-internal.so \
    vendor/micromax/A109/proprietary/vendor/lib/libsyscore.so:system/vendor/lib/libsyscore.so \
    vendor/micromax/A109/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_AESCipher.so:system/vendor/lib/libvlife_AESCipher.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_ffmpeg.so:system/vendor/lib/libvlife_ffmpeg.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_jpeg.so:system/vendor/lib/libvlife_jpeg.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_openglutil.so:system/vendor/lib/libvlife_openglutil.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_png.so:system/vendor/lib/libvlife_png.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_render.so:system/vendor/lib/libvlife_render.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_render2.so:system/vendor/lib/libvlife_render2.so \
    vendor/micromax/A109/proprietary/vendor/lib/libvlife_sdl.so:system/vendor/lib/libvlife_sdl.so \
    vendor/micromax/A109/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/micromax/A109/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/micromax/A109/proprietary/vendor/lib/libww.so:system/vendor/lib/libww.so \
    vendor/micromax/A109/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_PACKAGES += \
    CleanMaster_New \
    GamesClub_v1 \
    Getit_9Apr14 \
    MAd_v2.0.0_live_all \
    Marbell_IG-IW \
    MiGames_in_Released_IW \
    MiLive \
    OperaBrandingProvide-Micromax \
    Reverie_A109_KK \
    Reverie_SmartPad_A109_KK \
    SwiftKey \
    bookMyShow \
    ggj_android_all_multilang \
    hike \
    moffice_ml-IW \
    operamini_IW
